# An array is a variable with lots of values

Let's suppose you had a class of 30 first-graders, and you wanted to record each of their heights at the beginning of the semester for a class science project. 

You *could* store this information like so:

`BethInitialHeight = 42`

`DavidInitialHeight = 45`

`DominiqueInitialHeight = 46`

`TanishaIniitalHeight = 43`

`...`

taking up 30 lines to set up your data. If you wanted to repeat this project next school year, you would presumably need to change all these variable names... Time consuming. It doesn't get much better if you use numbers instead, since you'd still have 30 lines like

`InitialHeight1 = 42`

`InitialHeight2 = 45`

`InitialHeight3 = 46`

`IniitalHeight4 = 43`

`...``

and you would need to type out each one any time you wanted to calculate an average, create a bar graph, etc.

You would likely find it more convenient to store this data set in an **array**. The following code cell sets up an array of student height data.

In [1]:
%precision 3 
import numpy as np # Import the numpy library, where arrays live.

# Create an array with the listed elements.
StudentHeights = np.array([42,45,46,43,41,48,40,44,47,42,45,43,41,42])

# The whole array is...
StudentHeights

array([42, 45, 46, 43, 41, 48, 40, 44, 47, 42, 45, 43, 41, 42])

In [2]:
# The second element is...
StudentHeights[1]

45

In [3]:
# Elements 3 through 13 are...
StudentHeights[3:14]

array([43, 41, 48, 40, 44, 47, 42, 45, 43, 41, 42])

## Checkpoint

Describe the printed output of these cells. What information does each output tell you? How does the code tell Python to produce this output?

Modify the last code cell above to show you elements 6 through 10 of the array.

An important thing to notice about Python arrays is that **they begin counting at 0 instead of 1**. What happens when you ask for ``StudentHeights[0]``?

## Common errors to watch for.

The most common error people run into with arrays is **asking Python for an index that isn't there**. Where does this error occur in the code cell below? How can you tell?

In [4]:
import numpy as np

# Look at https://numpy.org/doc/stable/reference/generated/numpy.linspace.html to learn about linspace.
ArrayA = np.linspace(0,1,100)
ArrayB = np.linspace(1,2,30)
ArrayA, ArrayB

(array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
        0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
        0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
        0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
        0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
        0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
        0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
        0.70707071, 0.71717172, 0.72727273, 0.73

In [5]:

ArrayA[0] = ArrayA[0] + ArrayB[0]

ArrayA[30] = ArrayB[31]**2

ArrayA[60] = ArrayB[39] / ArrayB[10]

ArrayA

IndexError: index 31 is out of bounds for axis 0 with size 30

# Disucssion

What mathematical properties used in the classroom that could the array be used to decribe?

Name three physical elements that could can be modeled as a array.
